version: "3"

services:
  django:
    build:
      context: ./banks_users_be
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: pgdb
    ports:
      - "5432:5432"

  nextjs:
    build:
      context: ./banks_users_fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
