version: "3"
services:
  django-postgres:
    image: postgres:latest
    container_name: django-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  django:
    build:
      context: ./banks_users_be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - django-postgres

  nextjs:
    build:
      context: ./banks_users_fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
