# Generated by Django 5.0 on 2023-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, unique=True, verbose_name='bank_name')),
                ('routing_number', models.CharField(max_length=100, unique=True, verbose_name='routing_number')),
                ('swift_bic', models.CharField(max_length=100, unique=True, verbose_name='swift_bic')),
            ],
        ),
    ]
